---
- name: This is a playbook for cloning a vm in RHEV
  hosts: localhost
  gather_facts: False
  vars:
    machine_state: present
    host_memory: 2
    hostname_prefix: rhel
    sequence_start: 1
    sequence_end: 3

  tasks:
    - block:
      - include_vars: ovirt_Password.yml
      
      - name: Obtain SSO token using username/password creds.
        ovirt_auth:
          url: https://rhvm.internal.croftvillas.com/ovirt-engine/api
          username: admin@internal
          ca_file: pki-resource.cer
          password: "{{ ovirt_password }}"


      - name: This task clones a machine in RHEV
        ovirt_vms:
          auth: "{{ ovirt_auth }}"
          state: "{{ machine_state }}"
          cluster: "Cluster01"
          name: "{{ item }}"
          template: rhel7_template
          memory: "{{ host_memory }}GiB"
          cloud_init:
            host_name: "{{ item }}.internal.croftvillas.com"
        async: '300'
        poll: '0'
#        with_items:
        with_sequence: start="{{ sequence_start }}" end="{{ sequence_end }}" format="{{ hostname_prefix }}%02d"
        register: new_vms

      - name: 'Debug'
        debug:
          msg: '{{ new_vms }}'
          verbosity: '4'

      - name: Check status
        async_status: jid={{ item.ansible_job_id }}
        register: job_result
        until: job_result.finished
        retries: 100
        delay: 15
        with_items: "{{ new_vms.results }}"

      - name: Tag these vms so they can be identified in the inventory
        ovirt_tags:
          auth: "{{ ovirt_auth }}"
          name: "group_{{ hostname_prefix }}"
          state: attached
          vms:
            - "{{ item }}"
        with_sequence: start="{{ sequence_start }}" end="{{ sequence_end }}" format="{{ hostname_prefix }}%02d"
        when: machine_state == "present"
      
      always:
      - name: Always revoke the SSO token
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
