- name: This playbook installs the ovirt-agent on all the subscribed systems
  hosts: "tag_group_{{ hostname_prefix | default('all') }}"
  become: yes

  tasks:
    - name: Install the ovirt-agent using yum
      yum:
        state: latest
        name: rhevm-guest-agent-common
      notify: Start ovirt-agent
    - name: Make sure that the service is enabled
      service:
        name: ovirt-guest-agent
        enabled: yes

  handlers:
    - name: Start ovirt-agent
      service: 
        name: ovirt-guest-agent
        state: started
